"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['player.sh']
DATA_FILES = []
PACKAGES=['venv', 'data', 'src', 'view']

APP_VERSION = '1.0.0'

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': {}},
    setup_requires=['py2app'],
    packages=PACKAGES
)